name: CI Class 

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
    - name: Checkout do código 
      uses: actions/checkout@v3

    - name: Configurar Node.js 
      uses: actions/setup-node@v3
      with:
        node-version: '18' # Indica a versão do node a ser instalada

    - name: Instalar dependências  
      run: |
        cd Aula_8
        npm install

    - name: Executar testes
      run: |
        npm test